# Generated by Django 3.1.3 on 2021-04-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='phone',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
    ]
