# Generated by Django 3.1.3 on 2021-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_investor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_name',
            field=models.CharField(default='User Full Name', max_length=40),
            preserve_default=False,
        ),
    ]
