# Generated by Django 3.1.3 on 2021-04-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investor',
        ),
    ]
