# Generated by Django 3.1.3 on 2021-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portfolio', '0002_delete_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=350)),
                ('company_ticker', models.CharField(max_length=50)),
            ],
        ),
    ]
