# Generated by Django 3.1.3 on 2021-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_daily_realtime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_realtime_price',
            name='company_name',
            field=models.CharField(default='Default Value', max_length=350),
            preserve_default=False,
        ),
    ]
