# Generated by Django 3.1.3 on 2021-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_daily_realtime_price_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_realtime_price',
            name='market',
            field=models.CharField(choices=[('BSE', 'BSE'), ('NSE', 'NSE')], default='BSE', max_length=5),
            preserve_default=False,
        ),
    ]
