# Generated by Django 3.1.3 on 2021-04-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_investor_phone'),
        ('Portfolio', '0010_daily_realtime_price_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ltp', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.daily_realtime_price')),
            ],
        ),
    ]
