# Generated by Django 3.1.3 on 2021-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_holdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
