# Generated by Django 3.1.3 on 2021-04-09 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portfolio', '0012_auto_20210409_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='bought_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
