# Generated by Django 3.1.3 on 2021-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0013_auto_20210409_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_names',
            name='company_code',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AddField(
            model_name='company_names',
            name='market',
            field=models.CharField(choices=[('BSE', 'BSE'), ('NSE', 'NSE')], default='BSE', max_length=10),
        ),
    ]
