# Generated by Django 3.1.3 on 2021-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0014_auto_20210410_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_names',
            old_name='company_ticker',
            new_name='company_code_bse',
        ),
        migrations.RemoveField(
            model_name='company_names',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='company_names',
            name='market',
        ),
    ]
