# Generated by Django 3.1.3 on 2021-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0015_auto_20210410_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Names_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=350)),
                ('company_code_nse', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Company_Names',
            new_name='Company_Names_BSE',
        ),
    ]
