# Generated by Django 3.1.3 on 2021-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0016_auto_20210411_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='company_ticker',
            field=models.CharField(max_length=70),
        ),
    ]
