# Generated by Django 3.1.3 on 2021-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0017_auto_20210411_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='latest_trading_day',
            field=models.CharField(max_length=20),
        ),
    ]
