# Generated by Django 3.1.3 on 2021-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0018_auto_20210411_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='change',
            field=models.FloatField(null=True),
        ),
    ]
