# Generated by Django 3.1.3 on 2021-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0020_auto_20210413_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='bought_price',
            field=models.FloatField(default=0),
        ),
    ]
