# Generated by Django 3.1.3 on 2021-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0023_auto_20210415_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
