# Generated by Django 3.1.3 on 2021-04-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0025_auto_20210416_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
