# Generated by Django 3.1.3 on 2021-04-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0026_auto_20210416_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='bought_time',
            field=models.SlugField(default='djangodbmodelsfieldsdatetimefield'),
        ),
    ]
