# Generated by Django 3.1.3 on 2021-04-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0027_holdings_bought_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='bought_time',
        ),
    ]
