# Generated by Django 3.1.3 on 2021-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0028_remove_holdings_bought_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_staus',
            name='balance',
            field=models.FloatField(default=500000),
        ),
    ]
