# Generated by Django 3.1.3 on 2021-04-17 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0031_auto_20210417_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='history',
            name='profit',
        ),
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='gain',
            field=models.FloatField(default=0),
        ),
    ]
