# Generated by Django 3.1.3 on 2021-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0032_auto_20210417_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
