# Generated by Django 3.1.3 on 2021-04-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0033_history_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='change',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='change_percentage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='close',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='latest_trading_day',
            field=models.CharField(default=datetime.datetime(2021, 4, 19, 13, 0, 5, 599468), max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='prev_close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investor_staus',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investor_staus',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
