# Generated by Django 3.1.3 on 2021-04-23 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0035_auto_20210421_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='latest_trading_day',
            field=models.CharField(default=datetime.datetime(2021, 4, 23, 20, 8, 16, 281185), max_length=20, null=True),
        ),
    ]
