# Generated by Django 3.1.3 on 2021-05-03 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0036_auto_20210423_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='latest_trading_day',
            field=models.CharField(default=datetime.datetime(2021, 5, 3, 22, 1, 25, 665327), max_length=20, null=True),
        ),
    ]
