# Generated by Django 3.1.3 on 2021-05-09 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0038_auto_20210503_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_realtime_price',
            name='latest_trading_day',
            field=models.CharField(default=datetime.datetime(2021, 5, 9, 9, 5, 32, 818560), max_length=20, null=True),
        ),
    ]
